# Generated by Django 5.0.6 on 2024-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.TextField(),
        ),
    ]
