# Generated by Django 5.0.6 on 2024-07-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_clientcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcontact',
            old_name='phon',
            new_name='phone',
        ),
    ]
